sudo: false
language: node_js
node_js:
  - 6
  - 7
  - 8
  - stable

cache:
  bundle: true
  directories:
    - node_modules

before_script:
  - npm run build
  - npm install codecov --no-save
script:
  - npm test -- --coverage
after_script: codecov --token=$CODECOV_TOKEN
